# Generated by Django 4.1.3 on 2022-12-30 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_usermodel_password_alter_usermodel_re_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='re_password',
            field=models.IntegerField(),
        ),
    ]
